#!/bin/bash

GHP_DIR="$HOME/.ghp"
DOCKERFILE="$GHP_DIR/Dockerfile"
ALIAS_FILE="$GHP_DIR/aliases"

# Create Dockerfile if it doesn't exist
if [ ! -f "$DOCKERFILE" ]; then
  cat <<EOL > "$DOCKERFILE"
ARG PHP_VERSION=8.3-cli
FROM serversideup/php:\${PHP_VERSION} AS base

# Switch to root so we can do root things
USER root

# Save the build arguments as a variable
ARG USER_ID
ARG GROUP_ID

# Use the build arguments to change the UID
# and GID of www-data while also changing
# the file permissions for NGINX
RUN docker-php-serversideup-set-id www-data \${USER_ID}:\${GROUP_ID}
# Drop back to our unprivileged user
USER www-data
EOL
fi

function install_php() {
  local version=$1
  docker build \
    --build-arg USER_ID=$(id -u) \
    --build-arg GROUP_ID=$(id -g) \
    --build-arg PHP_VERSION="$version-cli" \
    -t "gpsystem/php:${version}-cli" . -f "$DOCKERFILE"

  echo "PHP $version installed."
}

function use_php() {
  local version=$1
  local php_alias="alias php=\"docker run --rm -it -v \$(pwd):/var/www/html --user \$(id -u):\$(id -g) --network host gpsystem/php:${version}-cli php\""
  local composer_alias="alias composer=\"docker run --rm -it -v \$(pwd):/var/www/html --user \$(id -u):\$(id -g) --network host gpsystem/php:${version}-cli composer\""

  # Update alias file
  echo "# PHP Aliases" > "$ALIAS_FILE"
  echo "$php_alias" >> "$ALIAS_FILE"
  echo "$composer_alias" >> "$ALIAS_FILE"

  echo "PHP $version aliases updated."

  # Notify user to run `source ~/.ghp/aliases` manually
  echo "Please run 'source $ALIAS_FILE' in your current terminal to update aliases."
}

function list_php() {
  docker images | grep 'gpsystem/php'
}

case $1 in
  install)
    install_php $2
    ;;
  use)
    use_php $2
    ;;
  list)
    list_php
    ;;
  *)
    echo "Usage: ghp {install|use|list} [version]"
    ;;
esac
