#!/bin/bash

GHP_DIR="$HOME/.ghp"
PHP_DIR="$GHP_DIR/php"
DOCKERFILE="$GHP_DIR/Dockerfile"
ALIAS_FILE="$GHP_DIR/aliases"

mkdir -p "$PHP_DIR"

# Create Dockerfile if it doesn't exist
if [ ! -f "$DOCKERFILE" ]; then
  cat <<EOL > "$DOCKERFILE"
ARG PHP_VERSION=8.3-cli
FROM serversideup/php:\${PHP_VERSION} AS base

# Switch to root so we can do root things
USER root

# Save the build arguments as a variable
ARG USER_ID
ARG GROUP_ID

# Use the build arguments to change the UID
# and GID of www-data while also changing
# the file permissions for NGINX
RUN docker-php-serversideup-set-id www-data \${USER_ID}:\${GROUP_ID}
# Drop back to our unprivileged user
USER www-data
EOL
fi

function install_php() {
  local version=$1
  local php_alias="alias php=\"docker run --rm -it -v \$(pwd):/var/www/html --user \$(id -u):\$(id -g) --network host gpsystem/php:${version}-cli php\""
  local composer_alias="alias composer=\"docker run --rm -it -v \$(pwd):/var/www/html --user \$(id -u):\$(id -g) --network host gpsystem/php:${version}-cli composer\""

  # Update alias file
  echo "# PHP Aliases" > "$ALIAS_FILE"
  echo "$php_alias" >> "$ALIAS_FILE"
  echo "$composer_alias" >> "$ALIAS_FILE"

  # Source the alias file in the current shell session
  if [ -n "$BASH_VERSION" ]; then
    source "$ALIAS_FILE"
  elif [ -n "$ZSH_VERSION" ]; then
    source "$ALIAS_FILE"
  else
    echo "Unsupported shell."
  fi

  echo "Now using PHP $version."
}

function use_php() {
  local version=$1
  echo "alias php=\"docker run --rm -it -v \$(pwd):/var/www/html --user \$(id -u):\$(id -g) --network host gpsystem/php:${version}-cli php\"" > "$ALIAS_FILE"
  echo "alias composer=\"docker run --rm -it -v \$(pwd):/var/www/html --user \$(id -u):\$(id -g) --network host gpsystem/php:${version}-cli composer\"" >> "$ALIAS_FILE"
  source "$ALIAS_FILE"
  echo "Now using PHP $version."
}

function list_php() {
  docker images | grep 'gpsystem/php'
}

case $1 in
  install)
    install_php $2
    ;;
  use)
    use_php $2
    ;;
  list)
    list_php
    ;;
  *)
    echo "Usage: ghp {install|use|list} [version]"
    ;;
esac
